// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package BlogEnginedb

import (
	"database/sql"
)

type Categories struct {
	CategoryID int64        `json:"category_id"`
	Name       string       `json:"name"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type Comments struct {
	CommentID int64         `json:"comment_id"`
	PostID    sql.NullInt64 `json:"post_id"`
	AuthorID  sql.NullInt64 `json:"author_id"`
	Content   string        `json:"content"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Likes struct {
	LikeID    int64         `json:"like_id"`
	PostID    sql.NullInt64 `json:"post_id"`
	AuthorID  sql.NullInt64 `json:"author_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type PostCategories struct {
	PostID     sql.NullInt64 `json:"post_id"`
	CategoryID sql.NullInt64 `json:"category_id"`
}

type PostTags struct {
	PostID sql.NullInt64 `json:"post_id"`
	TagID  sql.NullInt64 `json:"tag_id"`
}

type Posts struct {
	PostID      int64         `json:"post_id"`
	Title       string        `json:"title"`
	Content     string        `json:"content"`
	AuthorID    sql.NullInt64 `json:"author_id"`
	PublishedAt sql.NullTime  `json:"published_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
}

type PostsPostCategories struct {
	PostsPostID          int64 `json:"posts_post_id"`
	PostCategoriesPostID int64 `json:"post_categories_post_id"`
}

type PostsPostTags struct {
	PostsPostID    int64 `json:"posts_post_id"`
	PostTagsPostID int64 `json:"post_Tags_post_id"`
}

type Tags struct {
	TagID     int64        `json:"tag_id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Users struct {
	UserID       int64        `json:"user_id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
