// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package BlogEnginedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Categories struct {
	CategoryID int64              `json:"category_id"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Comments struct {
	CommentID int64              `json:"comment_id"`
	PostID    pgtype.Int8        `json:"post_id"`
	AuthorID  pgtype.Int8        `json:"author_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Likes struct {
	LikeID    int64              `json:"like_id"`
	PostID    pgtype.Int8        `json:"post_id"`
	AuthorID  pgtype.Int8        `json:"author_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PostCategories struct {
	PostID     pgtype.Int8 `json:"post_id"`
	CategoryID pgtype.Int8 `json:"category_id"`
}

type PostTags struct {
	PostID pgtype.Int8 `json:"post_id"`
	TagID  pgtype.Int8 `json:"tag_id"`
}

type Posts struct {
	PostID      int64              `json:"post_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	AuthorID    pgtype.Int8        `json:"author_id"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PostsPostCategories struct {
	PostsPostID          int64 `json:"posts_post_id"`
	PostCategoriesPostID int64 `json:"post_categories_post_id"`
}

type PostsPostTags struct {
	PostsPostID    int64 `json:"posts_post_id"`
	PostTagsPostID int64 `json:"post_Tags_post_id"`
}

type Tags struct {
	TagID     int64              `json:"tag_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Users struct {
	UserID       int64              `json:"user_id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
