// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: posts.sql

package BlogEnginedb

import (
	"context"
)

const checkIfLikeExists = `-- name: CheckIfLikeExists :one
SELECT EXISTS (SELECT 1 FROM "likes" WHERE "post_id" = $1 AND "author_id" = $2)
`

type CheckIfLikeExistsParams struct {
	PostID   int64 `json:"post_id"`
	AuthorID int64 `json:"author_id"`
}

func (q *Queries) CheckIfLikeExists(ctx context.Context, arg CheckIfLikeExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkIfLikeExists, arg.PostID, arg.AuthorID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const crateComment = `-- name: CrateComment :one
INSERT INTO comments(
    post_id,
    author_id,
    content
) VALUES (
    $1, $2, $3
) RETURNING comment_id, post_id, author_id, content, created_at
`

type CrateCommentParams struct {
	PostID   int64  `json:"post_id"`
	AuthorID int64  `json:"author_id"`
	Content  string `json:"content"`
}

func (q *Queries) CrateComment(ctx context.Context, arg CrateCommentParams) (Comments, error) {
	row := q.db.QueryRowContext(ctx, crateComment, arg.PostID, arg.AuthorID, arg.Content)
	var i Comments
	err := row.Scan(
		&i.CommentID,
		&i.PostID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createCategorie = `-- name: CreateCategorie :one
INSERT INTO categories(
    name
) VALUES (
    $1
) RETURNING category_id, name, created_at
`

func (q *Queries) CreateCategorie(ctx context.Context, name string) (Categories, error) {
	row := q.db.QueryRowContext(ctx, createCategorie, name)
	var i Categories
	err := row.Scan(&i.CategoryID, &i.Name, &i.CreatedAt)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts(
    title,
    content,
    author_id
) VALUES (
    $1, $2, $3
) RETURNING post_id, title, content, author_id, published_at, updated_at
`

type CreatePostParams struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	AuthorID int64  `json:"author_id"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Posts, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.Title, arg.Content, arg.AuthorID)
	var i Posts
	err := row.Scan(
		&i.PostID,
		&i.Title,
		&i.Content,
		&i.AuthorID,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags(
    name
) VALUES (
    $1
) RETURNING tag_id, name, created_at
`

func (q *Queries) CreateTag(ctx context.Context, name string) (Tags, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tags
	err := row.Scan(&i.TagID, &i.Name, &i.CreatedAt)
	return i, err
}

const getLikesForPost = `-- name: GetLikesForPost :one
SELECT COUNT(*) FROM likes 
WHERE post_id = $1
`

func (q *Queries) GetLikesForPost(ctx context.Context, postID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLikesForPost, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertLikePost = `-- name: InsertLikePost :one
INSERT INTO likes (
    post_id,
    author_id
) VALUES (
    $1, $2
) RETURNING like_id, post_id, author_id, created_at
`

type InsertLikePostParams struct {
	PostID   int64 `json:"post_id"`
	AuthorID int64 `json:"author_id"`
}

func (q *Queries) InsertLikePost(ctx context.Context, arg InsertLikePostParams) (Likes, error) {
	row := q.db.QueryRowContext(ctx, insertLikePost, arg.PostID, arg.AuthorID)
	var i Likes
	err := row.Scan(
		&i.LikeID,
		&i.PostID,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}
