// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: posts.sql

package BlogEnginedb

import (
	"context"
	"database/sql"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts(
    title,
    content,
    author_id
) VALUES (
    $1, $2, $3
) RETURNING post_id, title, content, author_id, published_at, updated_at
`

type CreatePostParams struct {
	Title    string        `json:"title"`
	Content  string        `json:"content"`
	AuthorID sql.NullInt64 `json:"author_id"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Posts, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.Title, arg.Content, arg.AuthorID)
	var i Posts
	err := row.Scan(
		&i.PostID,
		&i.Title,
		&i.Content,
		&i.AuthorID,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}
